doctrine:
    dbal:
        dbname: rms_dev
        host: localhost
        port: 3306
        user: root
        password: ''
        driver: pdo_mysql

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/AppBundle/Entity'
                prefix: 'App\AppBundle\Entity'
                alias: AppBundle
            inventory-management-bundle:
                is_bundle: false
                dir: '%kernel.project_dir%/src/InventoryManagementBundle/Entity'
                prefix: 'App\InventoryManagementBundle\Entity'
                alias: InventoryManagementBundle

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
